services:
  nextjs:
    build:
      context: .
    image: threedportfolio-next_portfolio_3001
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    volumes:
      - /app/node_modules
